repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.5.1'
    hooks:
      - id: prettier
        args: ['src/']
        additional_dependencies:
          - 'prettier@^2.5.1'
          - '@trivago/prettier-plugin-sort-imports@^3.2.0'
